# Generated by Django 4.2.18 on 2025-02-04 15:18

import apps.products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='product_images/', validators=[apps.products.models.validate_image_size]),
        ),
    ]
